name: sp_threshold_tuner
version: '0.1.0'
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - xarray
  - zarr
  - pyyaml
  - pillow
  - streamlit>=1.32
  - pip:
      - spatialproteomics>=0.8.0
